In [1]:
import os
os.getcwd()

'C:\\Users\\Rajnish tripathi'

# Creating the Array

In [2]:
import numpy as np
myarr=np.array([1,2,3,4,8])
print(myarr)


[1 2 3 4 8]


In [3]:
newarr=np.array([3,4,5,6],np.int32)
print(newarr)

[3 4 5 6]


In [4]:
myarr.shape


(5,)

In [5]:
myarr.dtype

dtype('int32')

# two dimensional array creation

In [6]:
listarr=np.array([[1,2,3],[3,4,5],[56,65,7]])
print(listarr)

[[ 1  2  3]
 [ 3  4  5]
 [56 65  7]]


In [7]:
listarr.shape

(3, 3)

In [8]:
listarr.size

9

# intrinsic numpy array creation objects

In [9]:
# initializing the array by zero
myarr=np.zeros((3,2))
print(myarr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [10]:
myarr.shape

(3, 2)

In [11]:
myarr.dtype

dtype('float64')

In [12]:
# creating an array of one's
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
# we can change the data type of the array elements
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [14]:
# numpy array in a range
rng=np.arange(12)
print(rng)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [15]:
# create an array of evenly spaced values
r=np.arange(10,30,5)
print(r)

[10 15 20 25]


In [16]:
# array elemenst eqaully related in a given range
lspace=np.linspace(1,23,5)
print(lspace)

[ 1.   6.5 12.  17.5 23. ]


In [17]:
# array with random elements
emp=np.empty((3,4))

In [18]:
emp

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
emp.shape

(3, 4)

In [20]:
emp.size

12

In [21]:
# empty arary like a given array
emp_like=np.empty_like(lspace)
print(emp_like)

[ 1.   6.5 12.  17.5 23. ]


In [22]:
# creation of an identity matrix
ide=np.identity(12,int)  # for integer type we use int

In [23]:
ide

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [24]:
# another way to create a identity matrix
np.eye(3) # it create a 3*3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# reshaping of an array

In [25]:
arr=np.arange(60)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [27]:
arr=arr.reshape(3,20)

In [28]:
arr.shape

(3, 20)

In [29]:
arr.size

60

In [30]:
arr.ravel() # for printing in a good shape in 1D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

# data types

In [31]:
np.int64   #Signed 64-bit integer types
np.float32 #Standard double-precision floating point
np.complex #Complex numbers represented by 128 floats
np.bool    #Boolean type storing TRUE and FALSE values
np.object  #Python object type
np.string_ #Fixed-length string type
np.unicode_ #Fixed-length unicode type

<ipython-input-31-7e466903aa03>:3: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.complex #Complex numbers represented by 128 floats
<ipython-input-31-7e466903aa03>:4: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool    #Boolean type storing TRUE and FALSE values
<ipython-input-31-7e466903aa03>:5: DeprecationWarning: `np.object

numpy.str_

# Axis in the array

In [32]:
# there is only one axis in 1D array i.e axis 0 
# And in 2D array there is two axises i.e axis 0 and axis 1 where the axis 0
# indicate the row of the matrix and axis 1 represent the column of the matrix


In [33]:
x=[[1,2,33],[4,5,6],[7,8,6]]


In [34]:
ar=np.array(x)

In [35]:
ar

array([[ 1,  2, 33],
       [ 4,  5,  6],
       [ 7,  8,  6]])

In [36]:
ar.sum(axis=0)

array([12, 15, 45])

In [37]:
ar.sum(axis=1)

array([36, 15, 21])

In [38]:
# for transpose the aray
ar.T

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [33,  6,  6]])

In [39]:
# flat create a iterator by which we can iterate over the arary
ar.flat

In [40]:
for i in ar.flat:
    print(i)

1
2
33
4
5
6
7
8
6


# inspecting your array

In [41]:
ar

array([[ 1,  2, 33],
       [ 4,  5,  6],
       [ 7,  8,  6]])

In [42]:
ar.astype(float) # convert an array to a different type

array([[ 1.,  2., 33.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  6.]])

In [43]:
# for finding the dimension of the array
ar.ndim

2

In [44]:
# for finding the total bytes consumes
ar.nbytes

36

In [45]:
n=np.array([2,3,43,5,432])

In [46]:
# for finding the index of the max value in the array
n.argmax()

4

In [47]:
n.argmin()

0

In [48]:
# it gives the sorting index of the array
n.argsort()

array([0, 1, 3, 2, 4], dtype=int64)

In [49]:
ar

array([[ 1,  2, 33],
       [ 4,  5,  6],
       [ 7,  8,  6]])

In [50]:
# argmin and argmin in 2D array
ar.argmax()

2

In [51]:
#in 2D matrix first it convert it in the a 1D then give the index forexample
# if the index of the (1,1 ) is 4 .

In [52]:
ar.argmin()

0

In [53]:
# argmin and argmax with the axis
ar.argmax(axis=0)

array([2, 2, 0], dtype=int64)

In [54]:
ar.argmin(axis=0)

array([0, 0, 1], dtype=int64)

In [55]:
ar.argmax(axis=1)

array([2, 2, 1], dtype=int64)

In [56]:
ar.argsort(axis=0)

array([[0, 0, 1],
       [1, 1, 2],
       [2, 2, 0]], dtype=int64)

In [57]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [58]:
ar.ravel() # for printing in 1D 

array([ 1,  2, 33,  4,  5,  6,  7,  8,  6])

In [59]:
ar

array([[ 1,  2, 33],
       [ 4,  5,  6],
       [ 7,  8,  6]])

# mathematical operations in numpy

In [60]:
ar1=np.array([[1,2,3],[2,1,3],[1,1,1]])

In [61]:
ar2=np.array([[1,2,1],[1,2,3],[3,1,2]])

In [62]:
ar1

array([[1, 2, 3],
       [2, 1, 3],
       [1, 1, 1]])

In [63]:
ar2

array([[1, 2, 1],
       [1, 2, 3],
       [3, 1, 2]])

In [64]:
ar3=ar1+ar2 # addition

In [65]:
ar3

array([[2, 4, 4],
       [3, 3, 6],
       [4, 2, 3]])

In [66]:
np.add(ar1,ar2)

array([[2, 4, 4],
       [3, 3, 6],
       [4, 2, 3]])

In [67]:
# subtraction
ar1-ar2

array([[ 0,  0,  2],
       [ 1, -1,  0],
       [-2,  0, -1]])

In [68]:
np.subtract(ar1,ar2) 

array([[ 0,  0,  2],
       [ 1, -1,  0],
       [-2,  0, -1]])

In [69]:
# division 
ar1/ar2

array([[1.        , 1.        , 3.        ],
       [2.        , 0.5       , 1.        ],
       [0.33333333, 1.        , 0.5       ]])

In [70]:
np.divide(ar1,ar2)

array([[1.        , 1.        , 3.        ],
       [2.        , 0.5       , 1.        ],
       [0.33333333, 1.        , 0.5       ]])

In [71]:
# multiplication
ar1*ar2

array([[1, 4, 3],
       [2, 2, 9],
       [3, 1, 2]])

In [72]:
np.multiply(ar1,ar2)

array([[1, 4, 3],
       [2, 2, 9],
       [3, 1, 2]])

# square root of all the elements 

In [73]:
np.sqrt(ar3)

array([[1.41421356, 2.        , 2.        ],
       [1.73205081, 1.73205081, 2.44948974],
       [2.        , 1.41421356, 1.73205081]])

In [74]:
ar1.sum()

15

In [75]:
ar.max()

33

In [76]:
ar.min()

1

# Comparison

In [77]:
ar1==ar2 # element wise comparison

array([[ True,  True, False],
       [False, False,  True],
       [False,  True, False]])

In [78]:
ar1<5  # elements - wise comparison

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [79]:
np.array_equal(ar1,ar2) # array-wise comparison

False

# we can easily find the elements of the array

In [80]:
ar

array([[ 1,  2, 33],
       [ 4,  5,  6],
       [ 7,  8,  6]])

In [81]:
np.where(ar==1)

(array([0], dtype=int64), array([0], dtype=int64))

In [82]:
# it return a tuple of the elements
type(np.where(ar>5))

tuple

# Copying Arrays

In [83]:
b=ar.view() # create a view of the array with the same data

In [84]:
ar

array([[ 1,  2, 33],
       [ 4,  5,  6],
       [ 7,  8,  6]])

In [85]:
b

array([[ 1,  2, 33],
       [ 4,  5,  6],
       [ 7,  8,  6]])

In [86]:
# create a copy of the array
np.copy(ar)

array([[ 1,  2, 33],
       [ 4,  5,  6],
       [ 7,  8,  6]])

# Slicing

In [87]:
ar[0:2]

array([[ 1,  2, 33],
       [ 4,  5,  6]])

In [88]:
one=np.array([2,3,4,5])

In [89]:
one[0:2]

array([2, 3])

# Boolean indexing

In [90]:
ar

array([[ 1,  2, 33],
       [ 4,  5,  6],
       [ 7,  8,  6]])

In [91]:
ar[ar>5]  # select elements from arr greater than 5

array([33,  6,  7,  8,  6])

# Counting of the non zero elements

In [92]:
np.count_nonzero(ar)

9

In [93]:
# we can print the dimensin of the nonzero elements
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

# Adding / Removing Elements

In [94]:
a=np.array([2,3,4,5])

In [95]:
b=np.array([6,7,8])

In [96]:
np.append(a,b) # insert the array

array([2, 3, 4, 5, 6, 7, 8])

In [97]:
np.insert(a,3,234) # insert the item at the index

array([  2,   3,   4, 234,   5])

In [98]:
np.delete(a,2)  #

array([2, 3, 5])

In [99]:
ar

array([[ 1,  2, 33],
       [ 4,  5,  6],
       [ 7,  8,  6]])

In [100]:
np.delete(ar,1)

array([ 1, 33,  4,  5,  6,  7,  8,  6])

# Comparision of list and array size

In [101]:
import sys
py_ar=[1,2,3,4]
np_ar=np.array(py_ar)

In [102]:
# getsizeof used to find the size of an element
sys.getsizeof(1) * len(py_ar)

112

In [103]:
np_ar.itemsize * np_ar.size

16

In [104]:
# tolist convert the array into list
np_ar.tolist()

[1, 2, 3, 4]

# for finding more attributes and methods of numpy array

In [105]:
# search numpy array methods and attributes